Documents/events_r_us-master/events_r_us/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('events.urls')),
    path('admin/', admin.site.urls),
    path('', include('django_registration.backends.one_step.urls')),
    path('', include('django.contrib.auth.urls')),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

events/urls.py
from django.urls import path
from events import views

app_name = 'events'

urlpatterns = [
    path('', views.index, name='index'),
    path('about', views.about, name='about'),
    path('login/', views.login, name='login'),
	path('logout/', views.user_logout, name= 'logout'),
    path('add_event', views.add_event, name='add_event'),
    path('event/<int:id>/<slug:event_slug>/', views.show_event, name='show_event'),
    path('search', views.search, name='search'),
    path('manage_events', views.manage_events, name='manage_events'),
    path('event/<int:id>/edit', views.edit_event, name='edit_event'),
    path('event/<int:id>/delete', views.delete_event, name='delete_event'),
    path('edit_profile', views.edit_profile, name='profile'),
    path('password', views.change_password, name='change_password'),
    path('event/<int:id>/<slug:event_slug>/deletecomment/<int:comment_id>', views.delete_comment, name = 'delete_comment'),
]

Documents/events_r_us-master/events/models.py
from django.db import models
import datetime
import django
from django.core.exceptions import ValidationError
from django.contrib.auth.models import User

from django.contrib.auth.models import AbstractUser, PermissionsMixin
from django.conf import settings

from django.template.defaultfilters import slugify

# Create your models here.

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    profile_image = models.ImageField(upload_to='profile_image', blank=True)
    location = models.CharField(max_length=60, blank=True)

    def __str__(self):
        return self.user.username


class Category(models.Model):
    Name = models.CharField(max_length=30,primary_key=True)
    class Meta: verbose_name_plural = 'Categories'
    def __str__(self):
        return self.Name

class Event(models.Model):
    NAME_MAX_LENGTH = 100
    DESCRIPTION_MAX_LENGTH = 1250
    ADDRESS_MAX_LENGTH = 100

    EventID = models.AutoField(primary_key=True)
    UserID = models.ForeignKey(User, on_delete=models.CASCADE)
    EventName = models.CharField(max_length=NAME_MAX_LENGTH)
    Description = models.CharField(max_length=DESCRIPTION_MAX_LENGTH)
    Picture = models.ImageField(upload_to='event_image', blank=True)
    
    # Should be requested from API:
    Address = models.CharField(max_length=ADDRESS_MAX_LENGTH)
    Longitude = models.DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)
    Latitude = models.DecimalField(max_digits=22, decimal_places=16, blank=True, null=True)
    
    DateTime = models.DateTimeField(default=django.utils.timezone.now)
    Category = models.ForeignKey(Category, on_delete=models.CASCADE)
    Rating = models.IntegerField(default=0)

    EVENT_TYPES = (
        ('One-off','One-off'),
        ('Recurring','Recurring')
    )
    eventType = models.CharField(choices = EVENT_TYPES, max_length=9)

    slug = models.SlugField()

    def save(self, *args, **kwargs):
        self.slug = slugify(self.EventName)
        super(Event, self).save(*args, **kwargs)

    def __str__(self):
        return self.EventName

class EventRatings(models.Model):
    RatingChoices = [
        (0.5, 0.5),
        (1.0,1.0),
        (1.5,1.5),
        (2.0,2.0),
        (2.5,2.5),
        (3.0,3.0),
        (3.5, 3.5),
        (4.0,4.0),
        (4.5,4.5),
        (5.0,5.0)
    ]

    Rating = models.DecimalField(choices=RatingChoices, max_digits=2, decimal_places=1)
    UserID = models.ForeignKey(User, on_delete=models.CASCADE)
    EventID = models.ForeignKey(Event, on_delete=models.CASCADE)

    class Meta:
        unique_together = ("UserID", "EventID")


class Comment(models.Model):
    CommentID = models.AutoField(primary_key=True)
    EventID = models.ForeignKey(Event, on_delete=models.CASCADE)
    UserID = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    Comment = models.CharField(max_length=200)
    #ParentCommentID = models.ForeignKey(Comments, on_delete=models.CASCADE)
    def __str__(self):
        return self.CommentID 
    
        
        # validates the date ensuring it is not in past 
    def save(self, *args, **kwargs):
        if self.date < datetime.date.today():
            raise ValidationError("The date cannot be in the past!")
            super(Event, self).save(*args, **kwargs)

Documents/events_r_us-master/events/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout, update_session_auth_hash
from django.contrib.auth import login as auth_login
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django_registration.views import RegistrationView
from events.forms import UserForm, UserProfileForm, EventForm, SearchForm, ProfileUpdateForm, EditProfileForm
from events.helpers import haversine
from .models import User, Event, Category
from django.shortcuts import render_to_response
from django.template import RequestContext
from django.template import Context
from django.http import HttpResponseRedirect
from django.contrib.auth.forms import UserChangeForm,PasswordChangeForm



def index(request):
    form = SearchForm()
    return render(request, 'events/index.html', {'form' : form})


def signup(request):

	registered = False
	
	if request.method == 'POST':
		
		user_form = UserForm(request.POST)
		profile_form = UserProfileForm(request.POST)
		
		if user_form.is_valid() and profile_form.is_valid():
		
			user = user_form.save()
			
			user.set_password(user.password)
			
			user.save()
			
			profile = profile_form.save(commit=False)
			profile.user = user
			profile.save()
			
			registered = True
			
		else:
			
			print(user_form.errors, profile_form.errors)
			
	else:
		
		user_form = UserForm()
		profile_form = UserProfileForm()
		
	return render(request, 'events/sign-up.html', context = {'user_form': user_form, 'profile_form' : profile_form, 'registered':registered})

def user_logout(request):
    
    logout(request)
    
    return redirect(reverse('events:index'))
    
def login(request):
    
    if request.method == 'POST':
        
        username = request.POST.get('username')
        
        password = request.POST.get('password')
        
        user = authenticate(username=username, password=password)
        
        if user:
            
            if user.is_active:
            
                auth_login(request, user)
                
                return redirect(reverse('events:index'))
                
            else:
            
                return HttpResponse("Your events account is disabled")
                
        else:
        
            print(f"Invalid Login details: {username}, {password}")
            return HttpResponse ("Invalid login credentials")
            
    else:
    
        return render(request, 'events/login.html')

def search(request):
    form = SearchForm()

    if request.method == 'POST':
        form = SearchForm(request.POST)

        if form.is_valid():
            print(form.cleaned_data)

            # Basic search
            Latitude = form.cleaned_data['Latitude']
            Longitude = form.cleaned_data['Longitude']

            # Refined search
            withinDistance = form.cleaned_data['distance']
            sortBy = form.cleaned_data['sortBy']
            eventType = form.cleaned_data['eventType']
            category = form.cleaned_data['category']
            keywords = form.cleaned_data['keywords']

            # TODO: Delete debug prints to decrease database hits
            
            query = Event.objects.all()

            # Filter events based on refined search options
            print("Initial query: " + str(query))
            if category != None:
                query = query.filter(category = category)
                print("category: " + str(query))
            if (eventType != "" and eventType != "Any"):
                query = query.filter(eventType = eventType)
                print("eventType: " + str(query))

            # Event name keyword search
            if keywords != "":
                for keyword in keywords.split():
                    query = query.filter(EventName__icontains=keyword)

            if sortBy == "Date occuring":
                query = query.order_by('DateTime')
                print("sortBy: " + str(query))
            print("Final query: " + str(query))

            # For context dictionary
            events = []

            # Calculate distances for each event from the user
            for event in query:
                # Calculate distance between our location and the event location
                haversineDistance = haversine(Latitude, Longitude, event.Latitude, event.Longitude)
                # Filter results by distance if required.
                if withinDistance == "" or haversineDistance < int(withinDistance):
                    event.distance = haversineDistance
                    events.append(event)

            # We need to do this filter after calculating the distances
            if sortBy == "Distance":
                events.sort(key=lambda e: e.distance)

            return render(request, 'events/search.html', {'form': form, 'events_list': events})
        else:
            print(form.errors)

    return render(request, 'events/search.html', {'form': form})
    
def add_event(request):
    form = EventForm()

    if request.method == 'POST':
        form = EventForm(request.POST, request.FILES)

        if form.is_valid():
            print(form.cleaned_data)
            event = Event(
                UserID=request.user, 
                EventName=form.cleaned_data["EventName"],
                Description=form.cleaned_data["Description"],
                Address=form.cleaned_data["Address"],
                Picture=form.cleaned_data["Picture"],
                Longitude=form.cleaned_data["Longitude"],
                Latitude=form.cleaned_data["Latitude"],
                DateTime=form.cleaned_data["DateTime"],
                category=form.cleaned_data["CategoryList"],
                eventType=form.cleaned_data["eventType"],
                Rating=0,
                )
            event.save()
            return redirect(reverse('events:index'))
        else:
            print(form.errors)
        
    return render(request, 'events/add_event.html', {'form': form})
    
def edit_profile(request):
    if request.method == "POST":
        form = EditProfileForm(request.POST, instance=request.user)
        
        if form.is_valid():
            form.save()
            return redirect(reverse('events:index'))
    else:
        form = EditProfileForm(instance=request.user)
        args={'form':form}
        return render(request, 'events/profile.html',args)
    
def change_password(request):
    if request.method == "POST":
        form = PasswordChangeForm(data = request.POST, user=request.user)
        if form.is_valid():
            form.save()
            update_session_auth_hash(request,form.user)
            return redirect('events:index')
            
        else:
            form = PasswordChangeForm(user=request.user)
            args = {'form':form}
            return render(request, 'events/change_password.html',args)
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form':form}
        return render(request, 'events/change_password.html',args)
    
        

def index(request):

    form = SearchForm()

    return render(request, 'events/index.html', {'form' : form})



def signup(request):

	registered = False

	

	if request.method == 'POST':

		user_form = UserForm(request.POST)

		profile_form = UserProfileForm(request.POST)



		if user_form.is_valid() and profile_form.is_valid():

			user = user_form.save()

			user.set_password(user.password)

			user.save()

			

			profile = profile_form.save(commit=False)

			profile.user = user

			profile.save()

			

			registered = True

		else:

			print(user_form.errors, profile_form.errors)

	else:

		user_form = UserForm()

		profile_form = UserProfileForm()

	return render(request, 'events/sign-up.html', context = {'user_form': user_form, 'profile_form' : profile_form, 'registered':registered})



def user_logout(request):

    logout(request)

    return redirect(reverse('events:index'))

    

def login(request):

    if request.method == 'POST':

        username = request.POST.get('username')

        password = request.POST.get('password')

        

        user = authenticate(username=username, password=password)

        

        if user:

            if user.is_active:

                auth_login(request, user)

                return redirect(reverse('events:index'))

            else:

                return HttpResponse("Your events account is disabled")

        else:

            print(f"Invalid Login details: {username}, {password}")

            return HttpResponse ("Invalid login credentials")

    else:

        return render(request, 'events/login.html')







def search(request):

    form = SearchForm()



    if request.method == 'POST':

        form = SearchForm(request.POST)



        if form.is_valid():

            print(form.cleaned_data)



            # Basic search

            Latitude = form.cleaned_data['Latitude']

            Longitude = form.cleaned_data['Longitude']



            # Refined search

            withinDistance = form.cleaned_data['distance']

            sortBy = form.cleaned_data['sortBy']

            eventType = form.cleaned_data['eventType']

            category = form.cleaned_data['category']

            keywords = form.cleaned_data['keywords']



            # TODO: Delete debug prints to decrease database hits

            

            query = Event.objects.all()



            # Filter events based on refined search options

            print("Initial query: " + str(query))

            if category != None:

                query = query.filter(category = category)

                print("category: " + str(query))

            if (eventType != "" and eventType != "Any"):

                query = query.filter(eventType = eventType)

                print("eventType: " + str(query))



            # Event name keyword search

            if keywords != "":

templates/events/base.html
<!DOCTYPE html>
{% load static %}

<html>
  <head>
    <title>
	Events 'R' Us -
	{% block title_block %}
	{% endblock %}
    </title>
    <!-- Favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="{% static 'favicon/apple-icon-57x57.png' %}">
    <link rel="apple-touch-icon" sizes="60x60" href="{% static 'favicon/apple-icon-60x60.png' %}">
    <link rel="apple-touch-icon" sizes="72x72" href="{% static 'favicon/apple-icon-72x72.png' %}">
    <link rel="apple-touch-icon" sizes="76x76" href="{% static 'favicon/apple-icon-76x76.png' %}">
    <link rel="apple-touch-icon" sizes="114x114" href="{% static 'favicon/apple-icon-114x114.png' %}">
    <link rel="apple-touch-icon" sizes="120x120" href="{% static 'favicon/apple-icon-120x120.png' %}">
    <link rel="apple-touch-icon" sizes="144x144" href="{% static 'favicon/apple-icon-144x144.png' %}">
    <link rel="apple-touch-icon" sizes="152x152" href="{% static 'favicon/apple-icon-152x152.png' %}">
    <link rel="apple-touch-icon" sizes="180x180" href="{% static 'favicon/apple-icon-180x180.png' %}">
    <link rel="icon" type="image/png" sizes="192x192"  href="{% static 'favicon/android-icon-192x192.png' %}">
    <link rel="icon" type="image/png" sizes="32x32" href="{% static 'favicon/favicon-32x32.png' %}">
    <link rel="icon" type="image/png" sizes="96x96" href="{% static 'favicon/favicon-96x96.png' %}">
    <link rel="icon" type="image/png" sizes="16x16" href="{% static 'favicon/favicon-16x16.png' %}">
    <link rel="manifest" href="{% static 'favicon/manifest.json' %}">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="{% static 'favicon/ms-icon-144x144.png' %}">
    <meta name="theme-color" content="#ffffff">

	<!--
		Scripts/CSS
	-->
    <link href="{% static '\css\bootstrap.css' %}" rel="stylesheet">
    <link href="{% static '\css\override.css' %}" rel="stylesheet">
    <link href="{% static '\css\font-awesome.min.css' %}" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.bundle.min.js" integrity="sha384-6khuMg9gaYr5AxOqhkVIODVIvm9ynTT5J4V1cfthmT+emCG6yVmEZsRHdxlotUnm" crossorigin="anonymous"></script>

	{% block head_block %}
    {% endblock %}
  </head>
  <body>
    <!--
        Nav bar
    -->
    <nav class="navbar navbar-expand-lg navbar-light">
        <div class="d-flex flex-grow-1">
            <a class="navbar-brand d-lg-inline-block"href="{% url 'events:index' %}">
                <img src="{% static '/images/navbar-image.png' %}" height="55" alt="Events R Us logo">
            </a>
        </div>
        <div class="navbar-collapse flex-grow-1 text-right">
            <ul class="navbar-nav ml-auto flex-nowrap font-weight-bold text-uppercase">
                <li class="nav-item">
                    <a href="{% url 'events:about' %}" class="nav-link m-2">About</a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a href="{% url 'events:manage_events' %}" class="nav-link m-2">Manage Events</a>
                </li>
				<li class="nav-item">
                    <a href="{% url 'events:profile' %}" class="nav-link m-2">Account</a>
                </li>
				<li class="nav-item">
                    <a href="{% url 'events:logout' %}" class="nav-link m-2">Sign Out</a>
                </li>
				{% else %}
				<li class="nav-item">
                    <a href="{% url 'events:login' %}" class="nav-link m-2">Log in</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'django_registration_register' %}" class="nav-link m-2">Sign up</a>
                </li>
				{% endif %}

            </ul>
        </div>
    </nav>

	{% block body_block %}
	{% endblock %}
  </body>
</html>

templates/events/delete_comment.html
{% extends 'events/base.html' %}
{% load static %}

{% block title_block %}
    Comment deletion
{% endblock %}

{% block head_block %}
{% endblock %}

{% block body_block %}
<div class="container manage-event-box">
    {% if status == 1 %}
    <div class="alert alert-success" role="alert">
        Comment on <span class="font-weight-bold">{{ comment.EventID.EventName }}</span> deleted successfully!
    </div>
    {% elif status == 2 %}
    <div class="alert alert-danger" role="alert">
        The specified comment does not exist or has already been deleted!
    </div>
    {% elif status == 3 %}
    <div class="alert alert-danger" role="alert">
        You do not have permission to delete that comment!
    </div>
    {% endif %}
    <a type="button" href="{% url 'events:show_event' id=event.EventID event_slug=event.slug %}" class="btn btn-light">Back<a>
</div>
{% endblock %}

templates/events/delete_status.html
{% extends 'events/base.html' %}
{% load static %}

{% block title_block %}
    Event deletion
{% endblock %}

{% block head_block %}
{% endblock %}

{% block body_block %}
<div class="container manage-event-box">
    {% if status == 1 %}
    <div class="alert alert-success" role="alert">
        <span class="font-weight-bold">{{ event.EventName }}</span> deleted successfully!
    </div>
    {% elif status == 2 %}
    <div class="alert alert-danger" role="alert">
        The specified event does not exist or has already been deleted!
    </div>
    {% endif %}
    <a type="button" href="{% url 'events:manage_events' %}" class="btn btn-light">Return to events<a>
</div>
{% endblock %}

templates/events/event.html
{% extends 'events/base.html' %}
{% load static %}

{% block title_block %}
  {{ event.EventName }}
{% endblock %}

{% block head_block %}
    <script src="{% static '/js/submit_rating.js' %}"></script>
    <script src="{% static '/js/image_popup.js' %}"></script>

    <!-- Map JS/CSS -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/leaflet/1/leaflet.css" />
    <script src="https://cdn.jsdelivr.net/leaflet/1/leaflet.js"></script>
    <script src="{% static '/js/event_map.js' %}"></script>
    <script src="{% static '/js/reply_button.js' %}"></script>

{% endblock %}

{% block body_block %}
<div class="container event-container">
    <div id="event-header-image" class="height-crop event-image-shadow">
        <img src="{{ event.Picture.url }}" class="img-fluid"  id="event-image" alt="Event image">
    </div>

    <div id="event-image-popup" class="popup">
        <span class="close-popup"><i class="fa fa-times" aria-hidden="true"></i></span>

        <!-- Modal Content (The Image) -->
        <img class="popup-content" id="popup-image">
    </div>

    <div class="row">
      <!--
        Main body
      -->
      <div class="col-8">
        <div id="event-info">
          <h3>{{ event.EventName }}</h3>
          <h6>{{ event.category }}</h6>
          <p>{{ event.Description }}</p>
        </div>

        <!--
            Comment system :)
        -->
		<div class="card-body">
			<div id="comment-section">
				<h4>{{ comments.count }} comments</h4>
				<!--Comment display-->
				{% for comment in comments %}
				{% if not comment.ParentCommentID %}
				<div class="comments mt-2">
					<p class="font-weight-bold">
            {% if comment.UserID == event.UserID %}
						<p class = "font-weight-bold" style="color:green;">{{comment.UserID.username}}</p>
            {% else %}
            {{comment.UserID.username}}
            {% endif %}
						<span class="text-muted font-weight-normal">
							{{comment.CreatedOn}}
						</span>
					</p>
					{{comment.Comment | linebreaks }}
					<!--Reply button-->
					{% if user.is_authenticated %}
					<footer class="blockquote-footer">
						<button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm">Reply</button>
            {% if user == comment.UserID %}
            <a class="btn btn-danger btn-sm" href="{% url 'events:delete_comment' id=comment.EventID.EventID event_slug=comment.EventID.slug comment_id=comment.CommentID %}">Delete</a>
            {% endif %}
        	</footer>

					<div class="replied-comments container mt-2" style="display:none">
						<div class="from-group row">
							<form method="post">
								{% csrf_token %}
								{{commentForm.as_p}}
								<input type ="hidden" name="parent_id" value ="{{ comment.CommentID }}">
								<input class="btn btn-outline-dark btn-sm" type="Submit" value="Submit">
							</form>
						</div>
					</div>
					{% endif %}
					<!--Reply display-->
					<div class = "relpies ml-4">
					{% for reply in comment.replies.all %}
						<p class = "font-weight-bold mt-2">
              {% if reply.UserID == event.UserID %}
  						<p class = "font-weight-bold" style="color:green;">{{reply.UserID.username}}</p>
              {% else %}
              {{reply.UserID.username}}
              {% endif %}
						<span class= "text-muted font-weight-normal">
							{{reply.CreatedOn}}
						</span>
						</p>
						{{reply.Comment | linebreaks }}
						<!--Reply button-->
						{% if user.is_authenticated %}
						<footer class="blockquote-footer">
							<button type="button" name="button" class="reply-btn btn btn-outline-dark btn-sm">Reply</button>
              {% if user == reply.UserID %}
                <a class="btn btn-danger btn-sm" href="{% url 'events:delete_comment' id=reply.EventID.EventID event_slug=reply.EventID.slug comment_id=reply.CommentID %}">Delete</a>
              {% endif %}
						</footer>

						<div class="replied-comments container mt-2" style="display:none">
							<div class="from-group row">
								<form method="post">
									{% csrf_token %}
									{{commentForm.as_p}}
									<input type ="hidden" name="parent_id" value ="{{ reply.CommentID }}">
									<input class="btn btn-outline-dark btn-sm" type="Submit" value="Submit">
								</form>
							</div>
						</div>
						{% endif %}
					{% endfor %}
					</div>
				</div>
				{% endif %}
				{% endfor %}
				{% if user.is_authenticated %}
				<div class="card-body">
					<h5>Leave a comment</h5>
					<form method="post">
						{% csrf_token %}
						{{commentForm.as_p}}
						<input type="submit" value="Submit">
					</form>
				</div>
				{% else %}
				<div class="row">
					<p>You must be logged in to comment.</p>
				</div>
				{% endif %}
			</div>
        </div>
		</div>

      <!--
        Sidebar area
      -->
      <div class="col-4">
        <div class="card">
            <!--
                Map
            -->
            <input type="hidden" id="Latitude" name="Latitude" value="{{ event.Latitude }}">
            <input type="hidden" id="Longitude" name="Longitude" value="{{ event.Longitude }}">
            <div class="card-img-top" id="map-container"></div>

            <!--
              Event info body
            -->
            <div class="card-body">
                <h5 class="card-title">
                    {{ event.UserID.username }}</h5>
                <p class="card-text">
                    <i class="fa fa-calendar" aria-hidden="true"></i>
                    {{ event.DateTime }}
                </h6>
                <p class="card-text">
                    {{ event.Address }}
                </p>
            </div>
            <!--
              Rating system
            -->
            <div class="card-footer">
              {% if user.is_authenticated %}
                <form role="form" name="rating_form" id="rating_form" method="post" enctype="multipart/form-data" action="{% url 'events:show_event' id=event.EventID event_slug=event.slug %}">
                    {% csrf_token %}
                    <p class="card-text rating-head">Your rating:</p>
                    <fieldset class="rating" name="rating_set">
                      {{ form.rating.9.tag }}<label class ="full" for="{{ form.rating.9.id_for_label }}" title="5 stars"></label>
                      {{ form.rating.8.tag }}<label class="half" for="{{ form.rating.8.id_for_label }}" title="4.5 stars"></label>
                      {{ form.rating.7.tag }}<label class ="full" for="{{ form.rating.7.id_for_label }}" title="4 stars"></label>
                      {{ form.rating.6.tag }}<label class="half" for="{{ form.rating.6.id_for_label }}" title="3.5 stars"></label>
                      {{ form.rating.5.tag }}<label class ="full" for="{{ form.rating.5.id_for_label }}" title="3 stars"></label>
                      {{ form.rating.4.tag }}<label class="half" for="{{ form.rating.4.id_for_label }}" title="2.5 stars"></label>
                      {{ form.rating.3.tag }}<label class ="full" for="{{ form.rating.3.id_for_label }}" title="2 stars"></label>
                      {{ form.rating.2.tag }}<label class="half" for="{{ form.rating.2.id_for_label }}" title="1.5 stars"></label>
                      {{ form.rating.1.tag }}<label class ="full" for="{{ form.rating.1.id_for_label }}" title="1 star"></label>
                      {{ form.rating.0.tag }}<label class="half" for="{{ form.rating.0.id_for_label }}" title="0.5 stars"></label>
                    </fieldset>
                    {{ form.rating.errors }}
                </form>
              {% else %}
                <p class="card-text rating-head">You must be logged in to leave a rating</p>
              {% endif %}
            </div>
            <div class="card-footer">
              {% if num_of_ratings > 0 %}
                <h4>{{ total_rating }}<span id="small-max-rating">/5.0</span></h4>
                <p class="card-text">Average rating from {{ num_of_ratings }} user(s)</p>
              {% else %}
                <p class="card-text">No users have rated this event yet.</p>
              {% endif %}
            </div>
          </div>
      </div>
    </div>
  </div>
{% endblock %}

templates/events/index.html
{% extends 'events/base.html' %}
{% load static %}

{% block title_block %}
    Home
{% endblock %}

{% block head_block %}
    <script src="{% static '/js/get_location.js' %}"></script>
    <script src="https://cdn.jsdelivr.net/npm/places.js@1.18.1"></script>
{% endblock %}

{% block body_block %}
    <!--
        Image background
    -->
    <div id="bg-home"></div>

    <div class="d-flex justify-content-center">
        <div id="finder-box" class="jumbotron">

            <form role="form" name="search_form" id="search_form" method="post" action="{% url 'events:search' %}">
                {% csrf_token %}
                {% for hidden in form.hidden_fields %}
                    {{ hidden }}
                {% endfor %}
            </form>

            <div class="d-flex justify-content-center">
			<!--
				This button should request the user's location and make a request to the search view with the location data (map API)
            -->
                <button id="get_location_button" class="btn btn-lg btn-primary" type="button" onclick="getLocation()">Find local events 
                <i style="margin-left: 5px;" class="fa fa-location-arrow" aria-hidden="true"></i>
                </button>
            </div>


            <hr class="my-4">

			<!--
				TODO: Button sends the user's input and makes a request to the search view with the location data (Should incorporate map API)
			-->
            <div class="d-flex justify-content-center">
                <div class="row mb-3">
                    <div class="col-12 col-sm-8">
                        <input id="id_Address" type="text" placeholder="Find events in...">
                    </div>
                    <div class="col-2">
                        <button class="btn btn-primary" type="button" onclick="submitSearchPositon()">Search</button>
                    </div>
                </div>
                <script src="{% static '/js/address_autocomplete.js' %}"></script>
            </div>
        </div>
    </div>

    {% if user.is_authenticated == False %}
        <div class="d-flex justify-content-center m-0" id="about-box">
            <div class="row  m-0">
                <div class="col-12 text-center">
                    <h3>Sign up today to...</h3>
                </div>
                <div class="col-sm-4 text-center">
                    <i class="fa fa-star-o about-fa"></i>
                    <p>Rate local events</br>and ask questions</p>
                </div>
                <div class="col-sm-4 text-center">
                    <i class="fa fa-save about-fa"></i>
                    <p>Keep track of local events</br>you would like to attend</p>
                </div>
                <div class="col-sm-4 text-center">
                    <i class="fa fa-calendar-o about-fa"></i>
                    <p>Post your own events</br>and receive feedback from other users</p>
                </div>
            </div>
        </div>
    {% endif %}

{% endblock %}